#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void MainPanelOnSize( wxSizeEvent& event );
		void MainPanelOnUpdateUI( wxUpdateUIEvent& event );
		void functionOnChoice( wxCommandEvent& event );
		void a_scrollBarOnScroll( wxScrollEvent& event );
		void b_scrollBarOnScroll( wxScrollEvent& event );
		void x_startOnText( wxCommandEvent& event );
		void x_stopOnText( wxCommandEvent& event );
		void y_startOnText( wxCommandEvent& event );
		void y_stopOnText( wxCommandEvent& event );
		void z_startOnText( wxCommandEvent& event );
		void z_stopOnText( wxCommandEvent& event );
		void divideOnText( wxCommandEvent& event );
		void arrow_lengthOnScroll( wxScrollEvent& event );
		void auto_arrowsOnCheckBox( wxCommandEvent& event );
		void x_scrollBarOnScroll( wxScrollEvent& event );
		void y_scrollBarOnScroll( wxScrollEvent& event );
		void z_scrollBarOnScroll( wxScrollEvent& event );
		void addSurfaceOnCheckBox( wxCommandEvent& event );
		void saveOnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members

};

#endif // __GUIMyFrame1__
